### ISSUE TITLE
panic at get_merkle_proof()

### ISSUE THREAD

**Issue by adust09** [InternetMaximalism/intmax-zkp-core#8]
block_circuitにて、あるprev_block_number, block_numberの組み合わせでpanicになる。
例えば(prev_block_number, block_number)=(8,9)の場合
```
thread 'main' panicked at 'index out of bounds: the len is 8 but the index is 9', /Users/ts21/intmax-zkp-core/src/merkle_tree/tree.rs:48:44
stack backtrace:
   0: rust_begin_unwind
             at /rustc/40336865fe7d4a01139a3336639c6971647e885c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/40336865fe7d4a01139a3336639c6971647e885c/library/core/src/panicking.rs:142:14
   2: core::panicking::panic_bounds_check
             at /rustc/40336865fe7d4a01139a3336639c6971647e885c/library/core/src/panicking.rs:84:5
   3: <usize as core::slice::index::SliceIndex<[T]>>::index
             at /rustc/40336865fe7d4a01139a3336639c6971647e885c/library/core/src/slice/index.rs:242:10
   4: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/40336865fe7d4a01139a3336639c6971647e885c/library/alloc/src/vec/mod.rs:2627:9
   5: <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index
             at /rustc/40336865fe7d4a01139a3336639c6971647e885c/library/alloc/src/vec/mod.rs:2627:9
   6: intmax_zkp_core::merkle_tree::tree::get_merkle_proof
             at ./src/merkle_tree/tree.rs:48:44
   7: block_circuit::main
             at ./src/bin/block_circuit.rs:451:9
   8: core::ops::function::FnOnce::call_once
             at /rustc/40336865fe7d4a01139a3336639c6971647e885c/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

追記
(7,8)ではsliceとは関係のないpanicを検出した

```
start proving: block_proof
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `53248`,
 right: `0`: 53248 generators weren't run', /Users/ts21/.cargo/git/checkouts/plonky2-7767d84a5a370f2d/c31b014/plonky2/src/iop/generator.rs:90:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**元のissue**
https://github.com/InternetMaximalism/intmax-zkp/issues/56

**Comment by hrmk1o3** [comment]
デバッグ情報とても助かります！

メモ: prev_block_number が 2 のべきのときが怪しそう.

**Comment by hrmk1o3** [comment]
追記にある `53248 generators weren't run` は現在修正されています。

**Comment by hrmk1o3** [comment]
`block_number` だけを変更するのではなく `block_headers` も変更する必要がありました。

https://github.com/InternetMaximalism/intmax-zkp-core/blob/bf78ecc579ad9cda446a56f12298647fdbf07d74/src/bin/block_circuit.rs#L460

特定の block_number 以外で検証を通ったのは、 Merkle tree を構成するときに leaf の数が 2 のべきになるまで padding する処理が入っていたからです。
